repos:
  # Generic pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the latest version from https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: mixed-line-ending
      - id: check-added-large-files
        name: check for added large files
        description: Prevents giant files from being committed
        args: ['--maxkb=500']

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: main
    hooks:
      - id: markdownlint-cli2

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2  # Use the latest version
    hooks:
      - id: gitleaks
