tailscale:
  hostname: tka
  port: 8123
  stateDir: /tmp/tka-ts-state
  tailnet: sphinx-map.ts.net

server:
  debug: true

otel:
  endpoint: localhost:4317
  insecure: true

operator:
  namespace: tka-dev
  clusterName: tka-cluster
  contextPrefix: tka-context-
  userPrefix: tka-user-

api:
  retryAfterSeconds: 1
